name = "AutoHashEqualsCached"
uuid = "887ad303-ad3a-4bc5-965e-507c643d6945"
authors = ["Neal Gafter <neal@gafter.com> and contributors"]
version = "0.1.1"

[deps]
Rematch = "bfecab0d-fd4d-5014-a23f-56c5fae6447a"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
