name = "AutoHashEqualsCached"
uuid = "887ad303-ad3a-4bc5-965e-507c643d6945"
authors = ["Neal Gafter <neal@gafter.com> and contributors"]
version = "1.0.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.6"
